version: '3.8'

services:
  java-service:
    image: java-service-image
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
  python-service:
    image: python-service-image
    depends_on:
      java-service:
        condition: service_started
    environment:
      - JAVA_SERVICE_URL=http://java-service:8080/pipeline