version: '3.8'

services:
  java-service:
    image: java-service-image
    ports:
      - "8080:8080"
  python-service:
    image: python-service-image
    depends_on:
      - java-service
    environment:
      - JAVA_SERVICE_URL=http://java-service:8080/pipeline
