version: '3.8'

services:
  java-service:
    image: java-service-image
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
      - EVENT_LOG_PATH=${EVENT_LOG_PATH}
    volumes:
      - ${EVENT_LOG_FILE}:${EVENT_LOG_PATH}

  python-service:
    image: python-service-image
    depends_on:
      java-service:
        condition: service_started
    environment:
      - JAVA_SERVICE_URL=${JAVA_SERVICE_URL}

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  app-network:
