version: '3.8'

services:
  java-service:
    image: java-service-image
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "-H", "Content-Type: application/json", "-d", '{"hyperParamFilter": 0.5}', "http://localhost:8080/pipeline"]
      interval: 30s
      timeout: 10s
      retries: 5

  python-service:
    image: python-service-image
    depends_on:
      java-service:
        condition: service_healthy
    environment:
      - JAVA_SERVICE_URL=http://java-service:8080/pipeline
